services:
  - type: web
    name: parking-backend
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker server.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"